<a href="https://colab.research.google.com/github/sowrabh-adiga/all-Machine-learning-codes/blob/main/Sci_kit_learn_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
what_we_are_covering=['0. An end to end sci-kit learn workflow => DONE',
                      '1. Getting data ready => Done',
                      '2. Choose right esitmators => (under progress)',
                      '3. Fit the training data onto a model and make prediction/Classification',
                      '4. Evaluate the model',
                      '5. Improve a model',
                      '6. Save and load a trained model',
                      '7. Putting it all togather ']
what_we_are_covering             

['0. An end to end sci-kit learn workflow => DONE',
 '1. Getting data ready => Done',
 '2. Choose right esitmators => (under progress)',
 '3. Fit the training data onto a model and make prediction/Classification',
 '4. Evaluate the model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all togather']

#Check the following

####https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

#2) Choosing a proper model\estimator\algorithm for the problem
##* Sci-kit learn uses 'esitmator' synonymous with 'model' or 'algorithm'

##2.1) Picking a proper ML model for regression problem

In [ ]:
#import boston housing dataset
import pandas as pd

from sklearn.datasets import load_boston
boston = load_boston()
boston;

In [ ]:
boston_df = pd.DataFrame(boston['data'],columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
boston_df.head(10)

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2
5  0.02985   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.12   5.21    28.7
6  0.08829  12.5   7.87   0.0  0.524  ...  311.0     15.2  395.60  12.43    22.9
7  0.14455  12.5   7.87   0.0  0.524  ...  311.0     15.2  396.90  19.15    27.1
8  0.21124  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.63  29.93    16.5
9  0.17004  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.71  17.10    18.9

[10 rows x 14 columns]

In [ ]:
len(boston_df)

506

In [ ]:
#see the model selection map from sci-kit learn
#use Ridge regression
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

#setup Random seed
np.random.seed(42)

#Create data
x = boston_df.drop('target',axis=1)
y = boston_df['target']

#train,test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate a ridge model
model = Ridge()
model.fit(x_train,y_train)

#Check the score
model.score(x_test,y_test)


0.6662221670168522

#How to improve the score
#How to replace Ridge model, if it wasnt working

In [ ]:
#Trying Random forest model
from sklearn.ensemble import RandomForestRegressor

# setup a random seed
np.random.seed(42)

# Create the data
X = boston_df.drop("target",axis=1)
y = boston_df["target"]

# split data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Instantiate RandomForest model
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

# Evaluate the Random Forest Regressor
rf.score(X_test,y_test)

0.873969014117403

In [ ]:
# Ridge model V/s RandomForest
model.score(x_test,y_test)

0.6662221670168522

##Choosing Estimator for classification problem
###going to :
https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
len(heart_disease)

303

### Import "LinearSVC"

In [ ]:
from sklearn.svm import LinearSVC

#get seed
np.random.seed(42)

#Make data
x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate LinearSVC
clf = LinearSVC(max_iter=10000)
clf.fit(x_train,y_train)

# Eval the SVC
clf.score(x_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.8688524590163934

In [ ]:
import sklearn

##If doesnt work >> ensemble

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection as ms#               << important thing to remeber cuz the older files are deprecated. 
#get seed
np.random.seed(42)

#Make data
x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# split the data
x_train,x_test,y_train,y_test = ms.train_test_split(x,y,test_size=0.2)  # << changed here  

# Instantiate RandomForestClasifier
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

# Eval the SVC
clf.score(x_test,y_test)

0.8524590163934426

#*TIDBIT*:
##1) structured data --> ensemble methods
##2) unstructure data --> deep learning


#### 'x' also known as 'features','feature Variable','data'
#### 'y' also known as 'labels','Targets','target variable'

In [ ]:
# what_we_are_covering[3]  = '3. Fit the training data onto a model and make prediction/Classification ==> (Under Progress)'
# what_we_are_covering[2] = '2. Choose right esitmators => DONE'
what_we_are_covering

['0. An end to end sci-kit learn workflow => DONE',
 '1. Getting data ready => Done',
 '2. Choose right esitmators => (under progress)',
 '3. Fit the training data onto a model and make prediction/Classification',
 '4. Evaluate the model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all togather']

##Closer look @ fit method
## AKA training

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection as ms#               << important thing to remeber cuz the older files are deprecated. 
#get seed
np.random.seed(42)

#Make data
x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# split the data
x_train,x_test,y_train,y_test = ms.train_test_split(x,y,test_size=0.2)  # << changed here  

# Instantiate RandomForestClasifier
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

# Eval the SVC
clf.score(x_test,y_test)

fit method takes all the variables into consideration and analyses the output for corresponding inputs, in other works train the model for given data

#Make Predictions

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection as ms#               << important thing to remeber cuz the older files are deprecated. 
#get seed
np.random.seed(42)

#Make data
x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# split the data
x_train,x_test,y_train,y_test = ms.train_test_split(x,y,test_size=0.2)  # << changed here  

# Instantiate RandomForestClasifier
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

# Eval the SVC
clf.score(x_test,y_test)  # >>  predicting the y with x_test and comparing them with y_test to see how much it has changed


#2 ways to make predictions
## 1) predict()
## 2) predict_proba()

In [ ]:
#use model to make predictions
clf.predict([1,7,8,3,4])

ValueError: ignored

In [ ]:
x_test.tail()

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
249   69    1   2       140   254  ...      0      2.0      1   3     3
104   50    1   2       129   196  ...      0      0.0      2   0     2
300   68    1   0       144   193  ...      0      3.4      1   2     3
193   60    1   0       145   282  ...      1      2.8      1   2     3
184   50    1   0       150   243  ...      0      2.6      1   0     3

[5 rows x 13 columns]

In [ ]:
 clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
#compare the predictions
y_pred =  clf.predict(x_test)
n = np.mean(y_pred == y_test)
n

0.8524590163934426

In [ ]:
clf.score(x_test,y_test) - n

#or

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8524590163934426

In [ ]:
#use predict_proba

t_pred_proba = clf.predict_proba(x_test)
t_pred_proba 

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82],
       [0.14, 0.86],
       [0.36, 0.64],
       [0.95, 0.05],
       [0.99, 0.01],
       [0.47, 0.53],
       [0.26, 0.74],
       [0.7 , 0.3 ],
       [0.11, 0.89],
       [0.95, 0.05],
       [0.03, 0.97],
       [0.02, 0.98],
       [0.01, 0.99],
       [0.84, 0.16],
       [0.95, 0.05],
       [0.98, 0.02],
       [0.51, 0.49],
       [0.89, 0.11],
       [0.38, 0.62],
       [0.29, 0.71],
       [0.26, 0.74],
       [0.34, 0.66],
       [0.2 , 0.8 ],
       [0.22, 0.78],
       [0.83, 0.17],
       [0.15, 0.85],
       [0.94, 0.06],
       [0.92, 0.08],
       [0.96, 0.04],
       [0.62, 0.38],
       [0.46, 0.54],
       [0.89, 0.11],
       [0.44, 0.56],
       [0.16, 0.84],
       [0.33, 0.67],
       [0.08, 0.92],
       [0.13, 0.87],
       [0.17, 0.83],
       [0.18, 0.82],
       [0.38, 0.62],
       [0.32, 0.68],
       [0.77, 0.23],
       [0.39, 0.61],
       [0.  ,

#with REgression modeL

In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn import model_selection as ms#      
import numpy as np
np.random.seed(42)
import pandas as pd

from sklearn.datasets import load_boston
boston = load_boston()
# #create data
boston_df = pd.DataFrame(boston['data'],columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
# # boston_df.head(10)
x = boston_df.drop("target",axis =1)
y = boston_df['target']

#create test and training sets
x_test,x_train,y_test,y_train = ms.train_test_split(x,y,test_size=0.2) 

#Instantiate abd fit model
model = RandomForestRegressor().fit(x_train,y_train)

#make prediction
y_pred = model.predict(x_test)

In [7]:
y_pred[:10]

array([10.602, 21.753, 24.429, 14.095, 20.358, 25.265, 23.793, 25.109,
       10.952, 15.502])

In [9]:
np.array(y_test[:10])

array([12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,  8.7, 27.5])

In [10]:
np.mean(y_pred-np.array(y_test[:10]))

ValueError: ignored

In [11]:
# compare 
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

2.8664950495049513