<a href="https://colab.research.google.com/github/sowrabh-adiga/all-Machine-learning-codes/blob/main/sci_kit_learn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#End-to-end scikit learn work flow

In [ ]:
#Get data
import pandas as pd
import numpy as np
dataH = pd.read_csv("heart-disease.csv")
dataH

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
# Create a feature matrix "x"
x = dataH.drop("target",axis=1)
# Create a label matrix  "y"
y = dataH['target']

# Choose a proper model
##Classification

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

#default hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

#Fit the model to training data

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
#make prediction
y_label = clf.predict(np.array([0,2,3,4])) # the array sent must be of same lengthm

ValueError: ignored

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1])

#Evaluate the model

In [ ]:
clf.score(x_train,y_train)

1.0

In [ ]:
clf.score(x_test,y_test)

0.819672131147541

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.73      0.78        26
           1       0.82      0.89      0.85        35

    accuracy                           0.82        61
   macro avg       0.82      0.81      0.81        61
weighted avg       0.82      0.82      0.82        61



In [ ]:
confusion_matrix(y_test,y_pred)

array([[19,  7],
       [ 4, 31]])

In [ ]:
accuracy_score(y_test,y_pred)

0.819672131147541

#Improve the model

In [ ]:
np.random.seed(42)
for i in range(10,101,10):
  print(f"Trying model with {i} estimators...")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
  print(f"Model Accuracy on test set : {clf.score(x_test,y_test)*100} \n")
  

Trying model with 10 estimators...
Model Accuracy on test set : 83.60655737704919 

Trying model with 20 estimators...
Model Accuracy on test set : 80.32786885245902 

Trying model with 30 estimators...
Model Accuracy on test set : 78.68852459016394 

Trying model with 40 estimators...
Model Accuracy on test set : 78.68852459016394 

Trying model with 50 estimators...
Model Accuracy on test set : 80.32786885245902 

Trying model with 60 estimators...
Model Accuracy on test set : 80.32786885245902 

Trying model with 70 estimators...
Model Accuracy on test set : 81.9672131147541 

Trying model with 80 estimators...
Model Accuracy on test set : 81.9672131147541 

Trying model with 90 estimators...
Model Accuracy on test set : 81.9672131147541 

Trying model with 100 estimators...
Model Accuracy on test set : 80.32786885245902 



In [ ]:
#Save the model
import pickle as pic
pic.dump(clf,open("sample.pkl","wb"))

In [ ]:
loaded_model = pic.load(open("sample.pkl","rb"))
loaded_model.score(x_test,y_test)
loaded_model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
np.pi

3.141592653589793

In [ ]:
import warnings
warnings.filterwarnings ("ignore") #To remove any warnings

#Getting data ready to be used for machine learning
## 3 main things:
###1) Split the data into features and labels (usually 'x','y')
###2) Filling (also called imputing) or discarding missing values
###3) Converting non-numerical values to numerical values(also called feature encoding)

In [ ]:
dataH

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

#Get feature data and label data

In [ ]:
x = dataH.drop("target",axis=1)
y = dataH['target']

#Split into test,train data. 

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [ ]:
#Coverting string data to numbers encoding
dataC = pd.read_csv('car-sales-extended.csv')
dataC

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [ ]:
len(dataC)

1000

In [ ]:
dataC.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [ ]:
#split to x, y
x = dataC.drop('Price',axis=1)
y = dataC['Price']
#split test and train data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
#build a a model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor() 
model.fit(x_train,y_train)
model.score(x_test,y_test)
#Convert string to number

ValueError: ignored

#Encoder

In [ ]:
#Convert catagorical data to numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_data = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_data)],
                                remainder="passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [ ]:
dummies = pd.get_dummies(dataC[['Make','Colour','Doors']])


In [ ]:
dummies

Doors  Make_BMW  Make_Honda  ...  Colour_Green  Colour_Red  Colour_White
0        4         0           1  ...             0           0             1
1        5         1           0  ...             0           0             0
2        4         0           1  ...             0           0             1
3        4         0           0  ...             0           0             1
4        3         0           0  ...             0           0             0
..     ...       ...         ...  ...           ...         ...           ...
995      4         0           0  ...             0           0             0
996      3         0           0  ...             0           0             1
997      4         0           0  ...             0           0             0
998      4         0           1  ...             0           0             1
999      4         0           0  ...             0           0             0

[1000 rows x 10 columns]

In [ ]:
#split to x, y
# x = dataC.drop('Price',axis=1)
# y = dataC['Price']
#split test and train data


#-----------------dummies----------------------#
x_train,x_test,y_train,y_test = train_test_split(dummies,y,test_size=0.2)

In [ ]:
#build a a model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor() 
model.fit(x_train,y_train)
print(model.score(x_test,y_test))
print("with dummies")
#Convert string to number

0.24277834907546267
with dummies


In [ ]:
#split to x, y
# x = dataC.drop('Price',axis=1)
# y = dataC['Price']
#split test and train data


#-----------------transformed_x----------------------#
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)

In [ ]:
#build a a model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor() 
model.fit(x_train,y_train)
print(model.score(x_test,y_test))
print("with transformed_x")
#Convert string to number



#-------------much performs better--------#

0.3302155950897808
with transformed_x


#Deal with missing data in rael time


In [1]:
import pandas as pd

In [3]:
#import car sales missing data
dataM = pd.read_csv("car-sales-extended-missing-data.csv")
dataM.head(10)

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [5]:
dataM.isna().sum() #total number of empty value

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [6]:
# get X and Y
x = dataM.drop("Price",axis=1)
y = dataM['Price']

In [9]:
# Convert data -> numbers
#Convert catagorical data to numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_data = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_data)],
                                remainder="passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x

ValueError: ignored

In [11]:
# Fill 'NaN' with data
dataM['Make'].fillna('missing',inplace=True) 
dataM['Colour'].fillna('missing',inplace=True) 
dataM['Odometer (KM)'].fillna(dataM['Odometer (KM)'].mean(),inplace = True)
dataM['Doors'].fillna(4,inplace=True)

In [12]:
#Check again for missing data
dataM.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [13]:
# 'Price' columns are the ones we are trying to predict
# So we cannot fill it with NaN techniques
# So, drop those values.
dataM.dropna(inplace=True)

In [15]:
dataM.isna().sum()


Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [16]:
len(dataM)

950

In [17]:
x = dataM.drop('Price',axis=1)
y = dataM['Price']

In [19]:
# Convert data -> numbers
#Convert catagorical data to numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_data = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_data)],
                                remainder="passthrough")
transformed_x = transformer.fit_transform(dataM)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

#NaN Pre-processing with sci-kit learn

In [20]:
datM = pd.read_csv('car-sales-extended-missing-data.csv')
datM.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [22]:
datM.dropna(subset=['Price'], inplace=True)
datM.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [25]:
x = datM.drop('Price',axis=1)
y = datM['Price']
x

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW   Blue       192714.0    5.0
2     Honda  White        84714.0    4.0
3    Toyota  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996     NaN  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[950 rows x 4 columns]

##sci-kit learn NaN value replacement

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Categorical data => 'missing';; Numerical data => mean() or const
# define strategy
cat_imputer = SimpleImputer(strategy = 'constant',fill_value='missing')
door_imputer = SimpleImputer(strategy = 'constant',fill_value=4)
num_imputer = SimpleImputer(strategy = 'mean')

# define columns
cat_features = ['Make','Colour']
door_features = ['Doors']
num_features = ['Odometer (KM)']

# Create imputer (something that fills missing data)
imputer = ColumnTransformer([
                             ('cat_imputer',cat_imputer,cat_features),
                             ('door_imputer',door_imputer,door_features),
                             ('num_imputer',num_imputer,num_features)
])

#Transform the data
new_x = imputer.fit_transform(x)
new_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [30]:
dataF = pd.DataFrame(new_x,
                     columns=['Make','Colour','Doors','Odometer (KM)'])
dataF.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [31]:
# Convert data -> numbers
#Convert catagorical data to numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_data = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_data)],
                                remainder="passthrough")
transformed_x = transformer.fit_transform(dataF)
transformed_x

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [35]:
#now fit a model
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.3601941785108257